### ISSUE TITLE
Em không thể giải nén file 

### ISSUE THREAD

**Issue by dovuchauanh** [hieuvijjo/anki1000#2]
Em không biết làm sao để giải nén khi không có nút giải nén. Mọi kết quả em thu được chỉ là như hình bên dưới ạ.
![2019-12-31 (1)](https://user-images.githubusercontent.com/59312419/71624149-7618c100-2c24-11ea-86ab-0bdffa047685.png)
![2019-12-31](https://user-images.githubusercontent.com/59312419/71624182-9f395180-2c24-11ea-99c6-300b17708375.png)

**Comment by hieuvijjo** [comment]
Thử download lại cả 2 part rồi mới giải nén nhé:

> Sau khi download **cả hai phần** về, cả nhà giải nén thành 1 file duy nhất `Glossika_Fluency_1.apkg` và import file này vào trong Anki bằng cách chọn: `File > Import ...`

**Comment by hieuvijjo** [comment]
Anh sửa lại chỉ còn duy nhất 1 link rồi, em dùng link này:
https://drive.google.com/file/d/1wnSry2Z4R-O-3tujUXe1pXooW0Yl4qie/view?usp=sharing
