### ISSUE TITLE
Tập nghe với Audacity trong Anki & lỗi Anki mất âm thanh

### ISSUE THREAD

**Issue by yenhoang0124** [hieuvijjo/anki1000#3]
> 
![Annotation 2020-02-11 204309](https://user-images.githubusercontent.com/60928569/74241871-78843580-4d0f-11ea-8303-f98aa11d76aa.png)

**Comment by hieuvijjo** [comment]
Đây là em muốn đưa audio vào trong Audacity đúng không?
Em cần cài Audacity vào:
https://www.audacityteam.org
Và thêm add-ons này:
https://ankiweb.net/shared/info/1502086928

Sau khi cài add-ons xong, có thể chọn `Tools > Edit audios in Editor > Config` rồi nhấp vào chỗ `Change Editor Path` và chọn đường dẫn đến `Audacity`.

Ngoài ra cũng cần lưu ý bạn làm add-ons mở bằng Audacity này có thể đổi phím tắt, nên để ý xem trong `Tools > Edit audios in Editor` bạn ý đang dùng phím tắt gì.

**Comment by yenhoang0124** [comment]
từ đầu lúc em mở bài học để học cũng không nghe được ạ


Vào Th 3, 11 thg 2, 2020 vào lúc 20:51 Hieu Vijjo <
notifications@github.com> đã viết:

**Comment by hieuvijjo** [comment]
Vậy em thử vào `Tools > Add-ons` rồi tìm cái add-on `Control Audio Playback Speed` và thử `Toggle Enabled` nó để disable, rồi tắt Anki đi bật lại thử xem. Hình như cái add-on ý đang bị lỗi hay sao ý.

**Comment by yenhoang0124** [comment]
em cảm ơn thầy ạ! Chạy được rồi.

Vào Th 3, 11 thg 2, 2020 vào lúc 22:22 Hieu Vijjo <
notifications@github.com> đã viết:
